version: "3"

services:
  database:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: achatdb   
    ports:
      - 3306:3306
    

  spring_app:
    image: raniabenabdallah/achat
    container_name: achatspring
    restart: on-failure
    ports:
     - 8089:8089
    depends_on:
     - database

  angular_app:
    image: wassim19/achatfront:1.0
    container_name: achatangular
    restart: on-failure
    ports:
     - 4200:4200
    depends_on:
     - spring_app