version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    restart: unless-stopped
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=
     - MYSQL_DATABASE=achatdb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=


  spring_app:
    image: raniabenabdallah/achat
    container_name: achatspring
    restart: on-failure
    ports:
     - 8089:8089
    depends_on:
     - mysqldb

  angular_app:
    image: wassim19/achatfront:1.0
    container_name: achatangular
    restart: on-failure
    ports:
     - 4200:4200
    depends_on:
     - spring_app